# src/main/resources/application.yml

spring:
  datasource:
    # MySQL 연결 정보
    url: jdbc:mysql://localhost:3306/devjob?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root          # MySQL 사용자명
    password: Hong1221##  # MySQL 비밀번호 (본인 설정값으로 수정)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      # 엔티티 변경 시 테이블 자동으로 업데이트
    show-sql: true          # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        "[format_sql]": true  # 대괄호와 따옴표로 감싸서 명확하게 지정한다.
        "[highlight_sql]": true   # (선택) SQL 가독성을 높여주는 추가 옵션

data-api:
  public-data:
    base-url: https://apis.data.go.kr/1051000/recruitment
    service-key: "44bfd2d82b03c82343d4032b3e2321a0e7ee3f71dff737615f6f614d3246e43b"